spring.datasource:
  url: "jdbc:postgresql://localhost:5432/gb_shop"
  username: '{cipher}AQAXg58caoCrXyGCStUWYbNXGllPBGXCtJIaddyc2giFcvA+sQh729ze5WTVJZEVrJlBPGK4jlTlYJFnD4aw2f1r+IxmWXABNCJQM08UKgwKhQ5i8h2wty0GB3FkP6hJCOfWD893AFwcbr/MFqst6MQnDE7hOCdF1AKMkEJ/xWJQrVAkTpnNBE1skXZFpoba8YUcMYyVZA91jPyamYOvk6m1cXFbXJ/VIuvUsaniP1Sl88vIfbaCBeVQbHixebF0kk6AHhw9W6uQreQTFVVi3i7Q9pMr/k6uznnIXTeqCgOybJ9S+4lmzoG8V213sdAzzX/K5TSSJwJ4T8SuF3lamFzYSyxwRjjy2T6HB+AWcF9jjxsoLcgGsVc707m+OG8T30s='
  password: '{cipher}AQAXg58caoCrXyGCStUWYbNXGllPBGXCtJIaddyc2giFcvA+sQh729ze5WTVJZEVrJlBPGK4jlTlYJFnD4aw2f1r+IxmWXABNCJQM08UKgwKhQ5i8h2wty0GB3FkP6hJCOfWD893AFwcbr/MFqst6MQnDE7hOCdF1AKMkEJ/xWJQrVAkTpnNBE1skXZFpoba8YUcMYyVZA91jPyamYOvk6m1cXFbXJ/VIuvUsaniP1Sl88vIfbaCBeVQbHixebF0kk6AHhw9W6uQreQTFVVi3i7Q9pMr/k6uznnIXTeqCgOybJ9S+4lmzoG8V213sdAzzX/K5TSSJwJ4T8SuF3lamFzYSyxwRjjy2T6HB+AWcF9jjxsoLcgGsVc707m+OG8T30s='

gb.api:
  endpoint:
    base-uri: '127.0.0.1:8080'
app.setting: 'dv'